[package]
name = "joy"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
ggez = "0.5"

chrono = "0.4.9"
log = "0.4.8"
fern = "0.5.9"
